:wrench: Modify target from es5 to esnext
Because esbuild doesn't support es5

$ npm run build

> esbuild-sandbox@1.0.0 build
> esbuild src/app.tsx --bundle --minify --sourcemap --outfile=public/bundle.js

 > src/app.tsx:4:0: error: Transforming const to the configured target environment ("es5") is not supported yet
     4 │ const App = (props: { message: string }) => {
       ╵ ~~~~~
   tsconfig.json:14:14: note: The target environment was set to "es5" here
    14 │     "target": "es5",                                     /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
       ╵               ~~~~~

 > src/app.tsx:5:2: error: Transforming const to the configured target environment ("es5") is not supported yet
     5 │   const [count, setCount] = useState(0);
       ╵   ~~~~~
   tsconfig.json:14:14: note: The target environment was set to "es5" here
    14 │     "target": "es5",                                     /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
       ╵               ~~~~~

 > src/app.tsx:5:8: error: Transforming destructuring to the configured target environment ("es5") is not supported yet
     5 │   const [count, setCount] = useState(0);
       ╵         ^
   tsconfig.json:14:14: note: The target environment was set to "es5" here
    14 │     "target": "es5",                                     /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
       ╵               ~~~~~

 > src/app.tsx:6:2: error: Transforming const to the configured target environment ("es5") is not supported yet
     6 │   const increment = useCallback(() => {
       ╵   ~~~~~
   tsconfig.json:14:14: note: The target environment was set to "es5" here
    14 │     "target": "es5",                                     /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
       ╵               ~~~~~

4 errors